# Generated by Django 4.1.7 on 2023-04-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_reg',
            name='Address',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AddField(
            model_name='admin_reg',
            name='DOB',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin_reg',
            name='Firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='admin_reg',
            name='Lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admin_reg',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin_reg',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin_reg',
            name='confirmPassword',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='admin_reg',
            name='img',
            field=models.ImageField(null=True, upload_to='uimg'),
        ),
    ]
