# Generated by Django 3.2.11 on 2023-04-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
            ],
        ),
    ]
