# Generated by Django 4.1.7 on 2023-03-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=500)),
                ('State', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=500)),
                ('Panchayat', models.CharField(max_length=200)),
                ('DOB', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('confirmPassword', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='uimg')),
            ],
        ),
    ]
