# Generated by Django 4.1.1 on 2023-04-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_user_reg_voterid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='OTP',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
